/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as AnoLetivoRouteImport } from './routes/ano-letivo'
import { Route as ComunicadosRouteImport } from './routes/comunicados'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ResponsaveisRouteImport } from './routes/responsaveis'
import { Route as TurmasRouteImport } from './routes/turmas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const AnoLetivoRoute = AnoLetivoRouteImport.update({
  id: '/ano-letivo',
  path: '/ano-letivo',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicadosRoute = ComunicadosRouteImport.update({
  id: '/comunicados',
  path: '/comunicados',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsaveisRoute = ResponsaveisRouteImport.update({
  id: '/responsaveis',
  path: '/responsaveis',
  getParentRoute: () => rootRouteImport,
} as any)
const TurmasRoute = TurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/ano-letivo': typeof AnoLetivoRoute
  '/comunicados': typeof ComunicadosRoute
  '/dashboard': typeof DashboardRoute
  '/responsaveis': typeof ResponsaveisRoute
  '/turmas': typeof TurmasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/ano-letivo': typeof AnoLetivoRoute
  '/comunicados': typeof ComunicadosRoute
  '/dashboard': typeof DashboardRoute
  '/responsaveis': typeof ResponsaveisRoute
  '/turmas': typeof TurmasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/ano-letivo': typeof AnoLetivoRoute
  '/comunicados': typeof ComunicadosRoute
  '/dashboard': typeof DashboardRoute
  '/responsaveis': typeof ResponsaveisRoute
  '/turmas': typeof TurmasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alunos'
    | '/ano-letivo'
    | '/comunicados'
    | '/dashboard'
    | '/responsaveis'
    | '/turmas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alunos'
    | '/ano-letivo'
    | '/comunicados'
    | '/dashboard'
    | '/responsaveis'
    | '/turmas'
  id:
    | '__root__'
    | '/'
    | '/alunos'
    | '/ano-letivo'
    | '/comunicados'
    | '/dashboard'
    | '/responsaveis'
    | '/turmas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunosRoute: typeof AlunosRoute
  AnoLetivoRoute: typeof AnoLetivoRoute
  ComunicadosRoute: typeof ComunicadosRoute
  DashboardRoute: typeof DashboardRoute
  ResponsaveisRoute: typeof ResponsaveisRoute
  TurmasRoute: typeof TurmasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ano-letivo': {
      id: '/ano-letivo'
      path: '/ano-letivo'
      fullPath: '/ano-letivo'
      preLoaderRoute: typeof AnoLetivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicados': {
      id: '/comunicados'
      path: '/comunicados'
      fullPath: '/comunicados'
      preLoaderRoute: typeof ComunicadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsaveis': {
      id: '/responsaveis'
      path: '/responsaveis'
      fullPath: '/responsaveis'
      preLoaderRoute: typeof ResponsaveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turmas': {
      id: '/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof TurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunosRoute: AlunosRoute,
  AnoLetivoRoute: AnoLetivoRoute,
  ComunicadosRoute: ComunicadosRoute,
  DashboardRoute: DashboardRoute,
  ResponsaveisRoute: ResponsaveisRoute,
  TurmasRoute: TurmasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
